# Generated by Django 3.0.5 on 2020-04-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200429_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndividualContact',
        ),
    ]
