# Generated by Django 3.0.5 on 2020-05-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_individualcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='frequency_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='snooze',
            field=models.DateTimeField(null=True),
        ),
    ]
