# Generated by Django 3.0.5 on 2020-05-02 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200501_2242'),
        ('core', '0010_auto_20200430_2316'),
    ]

    operations = [
    ]
