# Generated by Django 3.0.5 on 2020-05-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20200502_0159'),
        ('core', '0010_auto_20200501_2242'),
    ]

    operations = [
    ]
